[[CURRENCIES]]
code="DOGE"
issuer="SC2UWPGWPPP7RHMJ5LS6KD6EYDQFWHOYCREGZEK2346LSVMCQIB6F76I"
name="PaiYouHao"
desc="This is paiyouhao token created on Pi Testnet."
image="https://b7f2mh.space.github.io/DOGE.png"
